5000014051PROVINCE OF AGUSAN DEL SUR              24017.00
5053598454ABELITA, ROFELYN G.                                   1982.00
5042128452BON, MERCELITA O.                                     2966.00
5042328453CHUA, EDDIE G.                                        4079.00
5042358457GEOLINA, JOEL A.                                      9475.00
5042338458GETUBIG, ROBERTO V.                                   2057.00
5042478451LAMZON, NATHANIEL G.                                  3458.00
